### ISSUE TITLE
actorSum 更改if區段得到結果不一樣

### ISSUE THREAD

**Issue by unromanticman** [ATeamCamp/Logbook#3]
trace actorSum 發現其中經過的函式catchActor更改if區塊位置得到結果會不相同

原本是這樣：
<img src="http://i.imgur.com/wvJ4d0h.jpg" />
<br>
交換過後：
<img src="http://i.imgur.com/e8rYCcq.jpg" />
<br>

本隻函式(catchActor)位置
<img src="http://i.imgur.com/7BCyH16.png">

<img src="http://i.imgur.com/5slMAaL.png"/>
敘述：
上面每個單個函式結果其他兩個if槓掉 執行結果
(左邊)我覺得怪的原因是 mbox 已經拉出不重覆的資料了(445)  結果竟然 比原本結果(sum:386)多
註：sum是 三個if都存在的結果

**Comment by s890506** [comment]
後來發現這是因為有些平台送來的 name 會有 "" 的情況所導致。
